[package]
name = "k8s-custom-metrics-apiserver"
version = "0.1.0"
edition = "2021"


[dependencies]
anyhow = "1.0"
axum = "0.7"
axum-server = { version = "0.7", features = ["tls-rustls"] }
k8s-openapi = { version = "0.22", features = ["latest"] }
k8s-metrics = { version = "0.18" }
rcgen = "0.13"


[dev-dependencies]
kube = { version = "0.93" }
kube-client-ext = "0.0.35"
tokio = { version = "1.39", features = ["full"] }


[features]
pedantic = []
